# [general]
# import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[window.padding]
x = 10
y = 10

[window]
decorations = "Buttonless"
blur = true
opacity = 0.95

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"
